config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
    # @reviews = @flats.reviews
  end

  def show
    @flat = Flat.find(params[:id])
    # @reviews = @flat.reviews
    # @review = Review.new
  end

  def new
    @flat = Flat.new
    # @review = Review.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :address, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">

      <h1 class ="d-flex justify-content-center my-5">All our flats (<%= @flats.count %>)</h1>
      <div class="cards">
        <% @flats.each do |flat|%>
          <div class="card mx-2">
            <div class="card-top">
              <div class="card-titles">
                  <h3><strong><%= flat.name %></strong></h2>
                  <p><%= flat.address %></p>
              </div>
              <div class="card-inline-informations d-flex justify-content-flex">
                  <i class="fa-solid fa-euro-sign px-1 py-3">  <%= flat.number_of_guests %></i>
                  <i class="fa-solid fa-user-group px-1 py-3">  <%= flat.price_per_night %></i>
              </div>
            </div>
            <div class="card-bottom">
              <div class="card-more-info">
                <%= link_to "More info", flat_path(flat) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">

  <h1 class ="d-flex justify-content-center mt-5">Add a flat</h1>

  <%= simple_form_for [@flat] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Add", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/flats/show.html.erb
<div class="container">
  <h1 class ="d-flex justify-content-center m-5"><%= @flat.name %></h1>

  <ul class="list-unstyled">
      <li><%= @flat.address %></li>
      <li><%= @flat.description %></li>
      <li><%= @flat.price_per_night %></li>
      <li><%= @flat.number_of_guests %></li>
  </ul>

  <br>
  <br>

  <%= link_to 'Back', flats_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/5eda4b705c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar-lewagon">
    <h4>Simple AirBnb</h4>
      <%= link_to 'Add Flat', new_flat_path %>
  </div>
    <%= yield %>
  </body>
</html>